# develop
default[:pixtavietnam_app][:ftp][:develop][:original_bucket_jp] = "pixtavietnam-upload-develop-jp"
default[:pixtavietnam_app][:ftp][:develop][:mirror_bucket_jp] = "pixtavietnam-upload-develop-mirror-jp"
default[:pixtavietnam_app][:ftp][:develop][:thumbnail_bucket] = "pixta-image-thumb-awsimport-jp-develop"
default[:pixtavietnam_app][:ftp][:develop][:illustration_files_api_url] = "http://dev-app02.pixtavietnam.com:3000/api/v2/illustration_files"
default[:pixtavietnam_app][:ftp][:develop][:footage_files_api_url] = "http://dev-app02.pixtavietnam.com:3000/api/v2/footage_files"
default[:pixtavietnam_app][:ftp][:develop][:photo_files_api_url] = "http://dev-app02.pixtavietnam.com:3000/api/v2/photo_files"
default[:pixtavietnam_app][:ftp][:develop][:convert_png_to_jpg_queue_name] = "develop_png_to_jpg"
default[:pixtavietnam_app][:ftp][:develop][:convert_png_to_jpg_queue_region] = "ap-southeast-1"

# staging
default[:pixtavietnam_app][:ftp][:staging][:original_bucket_jp] = "pixtavietnam-upload-test-jp"
default[:pixtavietnam_app][:ftp][:staging][:mirror_bucket_jp] = "pixtavietnam-upload-test-mirror-jp"
default[:pixtavietnam_app][:ftp][:staging][:thumbnail_bucket] = "pixta-image-thumb-awsimport-jp-devel"
default[:pixtavietnam_app][:ftp][:staging][:illustration_files_api_url] = "http://52.74.0.70/api/v2/illustration_files"
default[:pixtavietnam_app][:ftp][:staging][:footage_files_api_url] = "http://52.74.0.70/api/v2/footage_files"
default[:pixtavietnam_app][:ftp][:staging][:photo_files_api_url] = "http://52.74.0.70/api/v2/photo_files"
default[:pixtavietnam_app][:ftp][:staging][:convert_png_to_jpg_queue_name] = "staging_png_to_jpg"
default[:pixtavietnam_app][:ftp][:staging][:convert_png_to_jpg_queue_region] = "ap-southeast-1"

# production
default[:pixtavietnam_app][:ftp][:staging][:original_bucket_jp] = "pixtavietnam-upload-develop-jp"
default[:pixtavietnam_app][:ftp][:staging][:original_bucket_eu] = "pixtavietnam-upload-develop-eu"
default[:pixtavietnam_app][:ftp][:staging][:original_bucket_uswest] = "pixtavietnam-upload-develop-uswest"
default[:pixtavietnam_app][:ftp][:staging][:original_bucket_useast] = "pixtavietnam-upload-develop-useast"
default[:pixtavietnam_app][:ftp][:staging][:mirror_bucket_jp] = "pixtavietnam-upload-develop-mirror-jp"
default[:pixtavietnam_app][:ftp][:staging][:mirror_bucket_eu] = "pixtavietnam-upload-develop-mirror-eu"
default[:pixtavietnam_app][:ftp][:staging][:mirror_bucket_uswest] = "pixtavietnam-upload-develop-mirror-uswest"
default[:pixtavietnam_app][:ftp][:staging][:mirror_bucket_useast] = "pixtavietnam-upload-develop-mirror-useast"
default[:pixtavietnam_app][:ftp][:staging][:thumbnail_bucket] = "pixta-image-thumb-awsimport-jp"
default[:pixtavietnam_app][:ftp][:staging][:illustration_files_api_url] = "https://api.pixta.jp/v2/illustration_files"
default[:pixtavietnam_app][:ftp][:staging][:footage_files_api_url] = "https://api.pixta.jp/v2/footage_files"
default[:pixtavietnam_app][:ftp][:staging][:photo_files_api_url] = "https://api.pixta.jp/v2/photo_files"
default[:pixtavietnam_app][:ftp][:staging][:convert_png_to_jpg_queue_name] = "prod_png_to_jpg"
default[:pixtavietnam_app][:ftp][:staging][:convert_png_to_jpg_queue_region] = "ap-southeast-1"
